# Generated by Django 4.2.3 on 2023-07-29 14:52

from django.db import migrations
import users.manager


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.manager.UserManager()),
            ],
        ),
    ]
