exclude: 'venv-update'
repos:
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.(css|ts|tsx|bck|csv)$
    -   id: check-merge-conflict
    -   id: check-json
    -   id: debug-statements
    -   id: check-added-large-files
        args: [--maxkb=500]
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-yaml
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
        name: Reorder Python imports
-   repo: local
    hooks:
    -   id: cyclic_imports
        name: check cyclic imports
        entry: python base/scripts/check_cyclic_imports.py
        language: system
        files: \.py$
        pass_filenames: false